name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version_dry_run.outputs.new_tag }}
      new_version: ${{ steps.tag_version_dry_run.outputs.new_version }}
      release_type: ${{ steps.tag_version_dry_run.outputs.release_type }}
    steps:
      - uses: actions/checkout@v4
      - id: tag_version_dry_run
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          custom_release_rules: config:patch:Configuration Changes,chore:patch:Miscellaneous,
          dry_run: true

  create-release:
    runs-on: ubuntu-latest
    needs: [calculate-version]
    outputs:
      status: ${{ steps.failure.outputs.status }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      - id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.calculate-version.outputs.new_tag }}
          tag_prefix: ''
          custom_release_rules: config:patch:Configuration Changes,chore:patch:Miscellaneous,
      - uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ needs.calculate-version.outputs.new_tag }}
          name: Release ${{ needs.calculate-version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: false
          prerelease: false
      - id: failure
        if: ${{ failure() }}
        run: echo "status=failure" >> $GITHUB_OUTPUT

  bump-release-branch:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Rebase release branch
        uses: martincostello/rebaser@v1
        id: rebase

      - name: Push changes
        if: ${{ steps.rebase.outputs.result == 'success' }}
        run: git push --force-with-lease origin release
