name: Release

on:
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Rollback tag (e.g., X.Y.Z)'
        type: string

permissions:
  contents: write

jobs:
  validate-rollback-tag:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      status: ${{ steps.validate_tag.outputs.status }}
      rollback: ${{ steps.validate_tag.outputs.rollback }}
    steps:
      - name: Validate tag
        id: validate_tag
        run: |
          if [[ "${{ github.event.inputs.rollback_tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "TAG=${{ github.event.inputs.rollback_tag }}" >> $GITHUB_ENV
            echo "rollback=true" >> $GITHUB_OUTPUT
          else
            echo "Invalid rollback tag format. Expected format: X.Y.Z"
            echo "rollback=false" >> $GITHUB_OUTPUT
          fi

  calculate-version:
    if: ${{ needs.validate-rollback-tag.outputs.rollback == 'false' }}
    needs: [validate-rollback-tag]
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version_dry_run.outputs.new_tag }}
      new_version: ${{ steps.tag_version_dry_run.outputs.new_version }}
      release_type: ${{ steps.tag_version_dry_run.outputs.release_type }}
    steps:
      - uses: actions/checkout@v4
      - id: tag_version_dry_run
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          custom_release_rules: config:patch:Configuration Changes,chore:patch:Miscellaneous,
          dry_run: true

      - name: Update TAG Env
        run: |
          echo "TAG=${{ steps.tag_version_dry_run.outputs.new_tag }}" >> $GITHUB_ENV

  create-release:
    if: ${{ needs.validate-rollback-tag.outputs.rollback == 'false' }}
    runs-on: ubuntu-latest
    needs: [validate-rollback-tag, calculate-version]
    outputs:
      status: ${{ steps.failure.outputs.status }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      - id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.calculate-version.outputs.new_tag }}
          tag_prefix: ''
          custom_release_rules: config:patch:Configuration Changes,chore:patch:Miscellaneous,
      - uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ needs.calculate-version.outputs.new_tag }}
          name: Release ${{ needs.calculate-version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: false
          prerelease: false
      - id: failure
        if: ${{ failure() }}
        run: echo "status=failure" >> $GITHUB_OUTPUT

  bump-release-branch:
    runs-on: ubuntu-latest
    needs: [calculate-version, create-release, validate-rollback-tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Reset release branch to selected release
        run: |
          echo "Resetting release branch to $TAG..."
          git fetch origin --tags
          git reset --hard $TAG
          git push origin release --force
